### ISSUE TITLE
Cloudflare + Traefik setup

### ISSUE THREAD

**Issue by ElVit** [erik73/hassio-addons#140]
Hi,
Thanks for this nice addon. 
I have not really much experience with Mail servers and hoped you could help me with the setup. 

At the moment i have installed the [traefik addon](https://github.com/alex3305/home-assistant-addons/blob/master/traefik/DOCS.md) and using it in combination with a cloudflare account. In cloudflare I entered my own domain and can reach home assistant (and some of its addons) over a subdomain through traefik. 

Do you know a tutorial or can you please describe how to configure both (cloudflare and traefik) to get the mailserver addon working?

Thanks!

**Comment by erik73** [comment]
Hi. 
I have no experience with the traefik addon.
I think that you can find what you need if you read up on general mail server setup tutorials.
